version: "2"
services:
  ctfd:
    image: ctfd
    restart: always
    ports:
    - "80:8000"
    volumes:
    - ./ctfd/ctfd.db:/opt/CTFd/CTFd/ctfd.db
  # Attacks
  attack-rtlo:
    image: attack-rtlo:latest
    restart: always
    ports:
    - "3334:3333"
  # Reverse
  reverse-reverse1:
    image: reverse-reverse1:latest
    restart: always
    ports:
    - "3335:3333"
  # Web
  hackme:
    image: tobi312/rpi-nginx:latest
    restart: always
    depends_on:
    - hackme-php
    volumes:
    #getme
    - ./cmd/web/getme/www:/sites/getme
    - ./cmd/web/getme/nginx/default:/etc/nginx/sites-enabled/getme
    #login
    - ./cmd/web/login/www:/sites/login
    - ./cmd/web/login/nginx/default:/etc/nginx/sites-enabled/login
    #md5-1
    - ./cmd/web/md51/www:/sites/md51
    - ./cmd/web/md51/nginx/default:/etc/nginx/sites-enabled/md51
    #hackme
    - ./cmd/web/hackme/www:/sites/hackme
    - ./cmd/web/hackme/nginx/default:/etc/nginx/sites-enabled/default
    links:
    - hackme-php
    ports:
    #getme
    - "3401:81"
    #login
    - "3402:82"
    #hackme
    - "3400:80"
  hackme-php:
    image: tobi312/rpi-php:7.0-fpm
    restart: always
    depends_on:
    - hackme-mysql
    environment:
    #getme
    - "getme_flag=FLAG-VKqyzggSJJeDmcpUAgbR"
    #login
    - "login_flag=FLAG-cgr2dxABLEGnoEq1nzbE"
    #md51
    - "md51_flag=FLAG-D2SxIOT1L6msTdU1BIoT"
    #hackme
    - "FLAG_1=FLAG-9n2q2cXeWuWgob0TZAFs"
    - "FLAG_2=FLAG-kc4melGy9UEBNImkj75b"
    - "FLAG_3=FLAG-3OrIsMRduP6lSdWPbvVL"
    - "FLAG_4=FLAG-S7Uu3j1tdex0VlZSc98C"
    - "MYSQL_USERNAME=hackme"
    - "MYSQL_PASSWORD=GV0uwG5xBJSpX354cwGc"
    - "MYSQL_HOST=hackme-mysql"
    - "MYSQL_DB_NAME=hackme"
    volumes:
    #getme
    - ./cmd/web/getme/www:/sites/getme
    #login
    - ./cmd/web/login/www:/sites/login
    #md51
    - ./cmd/web/md51/www:/sites/md51
    #hackme
    - ./cmd/web/hackme/www:/sites/hackme
    links:
    - hackme-mysql
  hackme-mysql:
    image: jsurf/rpi-mariadb:latest
    restart: always
    volumes:
    - mdb:/var/lib/mysql
    - ./cmd/web/hackme/hackme.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: bWZfayMGZDqYCFYsMsKx
      MYSQL_USER: hackme
      MYSQL_PASSWORD: GV0uwG5xBJSpX354cwGc
      MYSQL_DATABASE: hackme

volumes:
  mdb: