version: "2"
services:
  challenge-validator:
    image: challenge-validator:latest
    restart: always
    ports:
    - "3333:3333"
  serverless-ctf:
    image: serverless-ctf:latest
    restart: always
    ports:
    - "80:3334"