version: "2"
services:
  ctfd:
    image: ctfd
    restart: always
    ports:
    - "80:8000"
    volumes:
    - ./ctfd/ctfd.db:/opt/CTFd/CTFd/ctfd.db
    - ./ctfd/uploads:/opt/CTFd/CTFd/uploads
  # Attacks
  attack-rtlo:
    image: attack-rtlo:latest
    restart: always
    ports:
    - "3334:3333"
  # Reverse
  reverse-reverse1:
    image: reverse-reverse1:latest
    restart: always
    environment:
    - "reverse1_flag=FLAG-gTwJDjCGPFfEruCQFs8z"
    ports:
    - "3335:3333"
  # Web
  explorer:
    image: resin/raspberrypi3-alpine:latest
    restart: always
    ports:
    - "3500:22"
    hostname: explorer
    command: >
      bash -c "apk update
      && apk --no-cache add openssh-server zip rsync openssh-client
      && mkdir /home/exp
      && adduser -h /home/exp -s /bin/bash -D exp 
      && echo 'exp:pwB!v^Kf0C2oBXpX178K#@gg9%L@acaD' | chpasswd
      && cd /home/exp
      && echo -e 'FLAG-faF5hvdVAtFELWWpc439' > flag.txt
      && zip --password 'password123' flag.zip -r flag.txt
      && rm flag.txt
      && /usr/bin/ssh-keygen -A
      && echo '' > /etc/motd
      && /usr/sbin/sshd -D"
  hackme:
    image: tobi312/rpi-nginx:latest
    restart: always
    depends_on:
    - hackme-php
    volumes:
    #hackme
    - ./cmd/web/hackme/www:/sites/hackme
    - ./cmd/web/hackme/default:/etc/nginx/sites-enabled/default
    #getme
    - ./cmd/web/getme/www:/sites/getme
    - ./cmd/web/getme/default:/etc/nginx/sites-enabled/getme
    #login
    - ./cmd/web/login/www:/sites/login
    - ./cmd/web/login/default:/etc/nginx/sites-enabled/login
    #md5-1
    - ./cmd/web/md51/www:/sites/md51
    - ./cmd/web/md51/default:/etc/nginx/sites-enabled/md51
    #md5-2
    - ./cmd/web/md52/www:/sites/md52
    - ./cmd/web/md52/default:/etc/nginx/sites-enabled/md52
    #robots
    - ./cmd/web/robots/www:/sites/robots
    - ./cmd/web/robots/default:/etc/nginx/sites-enabled/robots
    #pager
    - ./cmd/web/pager/www:/sites/pager
    - ./cmd/web/pager/default:/etc/nginx/sites-enabled/pager
    #walloffire
    - ./cmd/web/walloffire/www:/sites/walloffire
    - ./cmd/web/walloffire/default:/etc/nginx/sites-enabled/walloffire
    #setme
    - ./cmd/web/setme/www:/sites/setme
    - ./cmd/web/setme/default:/etc/nginx/sites-enabled/setme
    #explorer
    - ./cmd/web/explorer/www:/sites/explorer
    - ./cmd/web/explorer/default:/etc/nginx/sites-enabled/explorer
    links:
    - hackme-php
    ports:
    #hackme
    - "3400:80"
    #getme
    - "3401:81"
    #login
    - "3402:82"
    #md5-1
    - "3403:83"
    #md5-2
    - "3404:84"
    #robots
    - "3405:85"
    #pager
    - "3406:86"
    #walloffire
    - "3407:87"
    #setme
    - "3408:88"
    #explorer
    - "3409:89"
  hackme-php:
    image: tobi312/rpi-php:7.0-fpm
    restart: always
    depends_on:
    - hackme-mysql
    environment:
    - "MYSQL_USERNAME=hackme"
    - "MYSQL_PASSWORD=GV0uwG5xBJSpX354cwGc"
    - "MYSQL_HOST=hackme-mysql"
    - "MYSQL_DB_NAME=hackme"
    - "STEALME_MYSQL_DB_NAME=stealme"
    #hackme
    - "FLAG_1=FLAG-9n2q2cXeWuWgob0TZAFs"
    - "FLAG_2=FLAG-kc4melGy9UEBNImkj75b"
    - "FLAG_3=FLAG-3OrIsMRduP6lSdWPbvVL"
    - "FLAG_4=FLAG-S7Uu3j1tdex0VlZSc98C"
    #getme
    - "getme_flag=FLAG-VKqyzggSJJeDmcpUAgbR"
    #login
    - "login_flag=FLAG-cgr2dxABLEGnoEq1nzbE"
    #md51
    - "md51_flag=FLAG-D2SxIOT1L6msTdU1BIoT"
    #md52
    - "md52_flag=FLAG-QkUjSIxarHRfi8KjvTq4"
    #robots
    - "robots_flag=FLAG-UTbN3ELwmeZINM1EelHJ"
    #pager
    - "pager_flag=FLAG-DwK7Gm4zL5QbsL6WdCpb"
    #walloffire
    - "walloffire_flag=FLAG-I46pBAhxule70HC5elnH"
    #setme
    - "setme_flag=FLAG-crcdVVEmXxan4H59QziB"
    volumes:
    #hackme
    - ./cmd/web/hackme/www:/sites/hackme
    #getme
    - ./cmd/web/getme/www:/sites/getme
    #login
    - ./cmd/web/login/www:/sites/login
    #md5-1
    - ./cmd/web/md51/www:/sites/md51
    #md5-2
    - ./cmd/web/md52/www:/sites/md52
    #robots
    - ./cmd/web/robots/www:/sites/robots
    #pager
    - ./cmd/web/pager/www:/sites/pager
    #walloffire
    - ./cmd/web/walloffire/www:/sites/walloffire
    #setme
    - ./cmd/web/setme/www:/sites/setme
    #explorer
    - ./cmd/web/explorer/www:/sites/explorer
    links:
    - hackme-mysql
  hackme-mysql:
    image: jsurf/rpi-mariadb:latest
    restart: always
    volumes:
    - mdb:/var/lib/mysql
    - ./cmd/web/hackme/hackme.sql:/docker-entrypoint-initdb.d/dump.sql
    - ./cmd/web/stealme/stealme.sql:/docker-entrypoint-initdb.d/stealme.sql
    environment:
      MYSQL_ROOT_PASSWORD: bWZfayMGZDqYCFYsMsKx
      MYSQL_USER: hackme
      MYSQL_PASSWORD: GV0uwG5xBJSpX354cwGc
      MYSQL_DATABASE: hackme
  breakme-web:
    image: tobi312/rpi-nginx:latest
    restart: always
    depends_on:
    - breakme-php
    volumes:
    - ./cmd/web/dropzone/www:/sites/dropzone
    - ./cmd/web/dropzone/default:/etc/nginx/sites-enabled/default
    links:
    - breakme-php
    ports:
    - "3410:90"
  breakme-php:
    image: tobi312/rpi-php:7.0-fpm
    restart: always
    volumes:
    - ./cmd/web/dropzone/www:/sites/dropzone
    entrypoint:
    - /bin/bash
    command: >
      -c "apt update
      && apt install python2.7 vim
      && echo 'FLAG-NamCn4RmIZPgVUhmGCrG' > /var/www/flag.txt
      && echo 'FLAG-uaUDBJWDH8B8Pkoe6fzP' > /root/flag.txt
      && chown www-data:www-data /var/www/flag.txt
      && chown root:root /usr/bin/vim.basic
      && chmod 4755 /usr/bin/vim.basic
      && chmod u+s /usr/bin/vim.basic
      && /entrypoint.sh php-fpm7.0"

volumes:
  mdb:
